spring.datasource.url=jdbc:postgresql://monorail.proxy.rlwy.net:19634/railway
spring.datasource.username=postgres
spring.datasource.password=uTjWMUmUKmqKoEFyVdqTMvaEOfJptFCt

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false